name: flutter_app_servicios_conductores
description: "Aplicaci√≥n para conductores - NETTALCO"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  go_router: ^14.2.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.14.0
  intl: ^0.19.0
  package_info_plus: ^8.0.0     # Info de la app instalada
  open_filex: ^4.5.0            # Abrir APK para instalar
  path_provider: ^2.1.0         # Directorio de descargas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon_n.png"
  adaptive_icon_background: "#1C224D"
  adaptive_icon_foreground: "assets/images/icon_n.png"
